c###genois.for
      SUBROUTINE GENOIS
      COMMON / FILES / LUI, LUO, LU2, LU5, LU6, LU15, LU16, LU20, LU25,
     A LU26, LU35
C--------------------------------
C
C     THIS ROUTINE COMPUTES THE COMBINED NOISE DISTRIBUTION - as prescribed
C       in ITS Report 87-212 "Updated NOISE Model for use in IONCAP"
C
CQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
      COMMON / CONTRL / IELECT(3), KTOUT(12), MONTHS(12), SUNSP(12),
     A IANTOU, ICARD, INTEG, IRED, ISOUT, ISPROC, ISSN, ITYPE, JDASH,
     B JFREQ, JLONG, KCARD, KRUN, MAPIN, MAXNAM, MONOLD, MOREM, MORES,
     C NUMNAM, NUPROC, MAXMET, MSPEC, M100
      COMMON /DON /ALATD, AMIN, AMIND, BTR, BTRD, DLONG, DMP, ERTR, GCD,
     1 GCDKM, PMP, PWR, TLAT, TLATD, TLONG, TLONGD, RSN, SIGTR, RLAT,
     2 RLATD,RLONG,RLONGD,BRTD,FLUX,ULAT,ULATD,ULONG,ULONGD,SSN,D90R,
     3 D50R,D10R,D90S,D50S,D10S
      COMMON/ANOIS/ATNU,ATNY,CC,TM,RCNSE,DU,DL,SIGM,SYGU,SYGL,KJ,JK
      COMMON /TON /ADJ, ADS, GNOS, GOT, REL, SL, SLS
     1, SPR, SU, SUS, XNOISE, ZNOISE, NF
      COMMON/FRQ/FREA(13),FREL(29),FREQ,JMODE,ITXRCP(2)
      COMMON / ION / IHRE, IHRO, IHRS, LUFP, METHOD, NOISE, NPSL
      COMMON / METSET / ITRUN, ITOUT, JTRUN(40), JTOUT(40)
      COMMON /RON /CLAT(5), CLONG(5), GLAT(5), RD(5), FI(3,5), YI(3,5),
     1HI(3,5), HPRIM(30,5), HTRUE(30,5), FVERT(30,5),KM,KFX, AFAC(30,5),
     2HTR(50,3), FNSQ(50,3)
      COMMON / TWO / F2D(16,6,6), P(29,16,8), ABP(2,9), DUD(5,12,5),
     A FAM(14,12), SYS(9,16,6), PERR(9,4,6)
      COMMON / ZON / ABPS(7), CREL(7), EFF(7), FLDST(7), GRLOS(7),
     1 HN(7), HP(7), PROB(7), RELY(7), RGAIN(7), SIGPOW(7), SN(7),
     2 SPRO(7), TGAIN(7), TIMED(7), TLOSS(7), B(7), FSLOS(7), ADV(7),
     3 OBF(7),NMODE(7),TLLOW(7),TLHGH(7)
CQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
      DIMENSION XNINT(4)
C.....MAN-MADE NOISE LEVELS
      DATA XNINT /76.8, 72.5, 67.2, 53.6/
C
      DATA DFAC,BFAC,CFAC /7.87384, 30.99872, 5.56765/
C
C        7.87384=SQRT(2 * 1.282**2 * 4.34294**2)
C
C       30.99872=(1.282**2)*(4.34294**2)
C
C        5.56765=4.34294 * 1.282
C
C.....DATA ARE FA VALUES AT 1 MHZ
C
C.....ATNU, ATNY ARE DB .GT. KTB FOR 1 MHZ
C.....ATNZ, ATNX ARE DB .GT. KTB FOR FREQ
C.....ATNOS, GNOS, XNOIS ARE DB .GT. KTB FOR ALL CALCULATIONS
C.....AND ARE CONVERTED TO DBW(1 HZ BWDTH) AT END OF ROUTINE
C.....UPPER LIMIT IS 55 MHZ FOR NOISE
      DUME=AMIN1(FREQ,55.)
      MAN=NOISE
C
C     FREQUENCY DEPENDENT ATMOSPHERIC NOISE
C
      IF (F2D(1,1,1)) 85,90,90
C.....NO IONOSPHERIC LONG TERM DATA BASE FILE
C.....FORCE MAN-MADE NOISE OR GALACTIC NOISE
   85 ATNOS=204.
      DUA=9.
      DLA=7.
      SMA=3.
      SUA=1.5
      SLA=1.5
      GO TO 95
   90 CONTINUE
C.....FREQUENCY DEPENDENCE
      CALL GENFAM(RLAT,KJ,DUME,ATNU,ATNZ,DU,DL,SIGM,SYGU,SYGL)
      write(luo,'(''genfam='',i5,3f10.4)') kj,freq,atnu,atnz
      CALL GENFAM(RLAT,JK,DUME,ATNY,ATNX,DX,DQ,SIGZ,SIGX,SIGSQ)
      write(luo,'(''genfam='',i5,3f10.4)') jk,freq,atny,atnx
C.....BEGIN INTERPOLATION ON LOCAL TIME
      SLOP=ABS(CC-TM)/4.
      ATNOS=ATNZ+(ATNX-ATNZ)*SLOP
      write(luo,'(''atnos='',5f10.4)') atnos,atnz,atnx,atnz,slop
      DUA=DU+(DX-DU)*SLOP
      DLA=DL+(DQ-DL)*SLOP
      SMA=SIGM+(SIGZ-SIGM)*SLOP
      SUA=SYGU+(SIGX-SYGU)*SLOP
      SLA=SYGL+(SIGSQ-SYGL)*SLOP
C.....END OF INTERPOLATION ON LOCAL TIME
C
C     (DUA/DFAC)**2=(DUA/1.282)**2/(2*4.34294**2)
C                  =(DUA/SQRT(2*1.282**2*4.34294**2))**2
C                  =(DUA/7.87384)**2
C
   95 AU=EXP((DUA/DFAC)**2+(ATNOS/4.34294))
      write(luo,'(''au='',4f15.4)') au,dua,dfac,atnos
      VU=AU*AU*(EXP(DUA*DUA/BFAC)-1.)
      AL=EXP((DLA/DFAC)**2+(ATNOS/4.34294))
C
C     DLA*DLA/BFAC=(DLA/1.282)**2/(4.34294)**2
C                 =DLA**2/30.99872
C
      VL=AL*AL*(EXP(DLA*DLA/BFAC)-1.)
C
C     GALACTIC NOISE
C
      IF(FREQ.le.FI(3,KFX)) then   !  FI(3,..) is F2 critical frequency
         GNOS=0.        !  GALACTIC NOISE DOES NOT PENETRATE
      else
         GNOS=52.-23.*ALOG10(FREQ)
      end if
      DUG=2.
      write(luo,'(''gnos='',f10.4)') gnos
      AT=EXP((DUG/DFAC)**2+(GNOS/4.34294))
      AU=AU+AT
      VU=VU+AT*AT*(EXP(DUG*DUG/BFAC)-1.)
      DLG=2.
      AT=EXP((DLG/DFAC)**2+(GNOS/4.34294))
      AL=AL+AT
      VL=VL+AT*AT*(EXP(DLG*DLG/BFAC)-1.)
      SMG=.5
      SUG=.2
      SLG=.2
C
C     MAN MADE NOISE
C
      MAN=NOISE
      XNOIS=MAN
      MA=IABS(MAN)
      ZNOISE=XNOIS
      IF (MAN) 120,114,115
C.....INDICATES -164 ON USER INPUT
  114 MA=4
      GO TO 120
C.....CONVERT 3 MHZ DB .LT. 1 WATT INPUT VALUE TO FA AT 1 MHZ
  115 XNOIS=204.0-XNOIS+13.22
C.....OBTAIN FA AT DESIRED FREQUENCY
      XNOIS=XNOIS-27.7*ALOG10(FREQ)
      GO TO 125
C.....NEGATIVE ON USER INPUT INDICATES INDEX
  120 MA=MIN0(4,MA)
      CONN=27.7
ccc      IF (MA.EQ.4) CONN=28.6    !  removed 4/13/2007 GRH
      XNOIS=XNINT(MA)-CONN*ALOG10(FREQ)
      ZNOISE=204.0-XNINT(MA)+13.22
  125 DUM=9.7
      AT=EXP((DUM/DFAC)**2+(XNOIS/4.34294))
      AU=AU+AT
      VU=VU+AT*AT*(EXP(DUM*DUM/BFAC)-1.)
      DLM=6.
      AT=EXP((DLM/DFAC)**2+(XNOIS/4.34294))
      AL=AL+AT
      VL=VL+AT*AT*(EXP(DLM*DLM/BFAC)-1.)
      SUM=1.5
      SMM=5.4
      SLM=1.5
CQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
C.....RECEIVER ANTENNA EFFICIENCY
C125PC      if(MSPEC.eq.125)then
c.......set rec EFF to 0. dB or unity
C125PC        reff=0.
C125PC      else
        CALL GAIN(2,0.0,FREQ,GDUM,reff)
C125PC      ENDIF
C.....SET ARRAY FOR ALL POSSIBLE MODES
      DO 196 IM=1,6
  196 EFF(IM) = reff
CQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
C.....NOW DETERMINATION OF NOISE LEVEL IS ITS-78 (HFMUFES4)
C.....SWITCH TO DB .GT. WATT
      write(luo,'(''atnos,gnos,xnois='',3f10.4)') atnos,gnos,xnois
      ATNOS=ATNOS-204.
      GNOS=GNOS-204.
      XNOIS=XNOIS-204.
      SIGTSQ=ALOG(1.+VU/(AU*AU))
      XRNSE=4.34294*(ALOG(AU)-SIGTSQ/2.)-204.
ccc      write(luo,'(''xrnse='',3f15.4)') xrnse,au,sigtsq
C.....UPPER DECILE
C
C     CFAC=4.34294*1.282
C         =5.56765
C
      DU=CFAC*SQRT(SIGTSQ)
      SIGTSQ=ALOG(1.+VL/(AL*AL))
C.....LOWER DECILE
      DL=CFAC*SQRT(SIGTSQ)
      IF (ITRUN-8) 205,210,205
  205 QPA=10.**((ATNOS-XRNSE)*0.1)
      QPG=10.**((GNOS-XRNSE)*0.1)
C.....PREDICTION ERRORS
C.....SIGM IS MEDIAN, SYGU IS UPPER AND SYGL IS LOWER
      QPM=10.**((XNOIS-XRNSE)*0.1)
      SIGM=SQRT((QPA*SMA)**2+(QPG*SMG)**2+(QPM*SMM)**2)
ccc      write(*,'(''sigm ='',4f10.4)') sigm,sma,smg,smm
ccc      write(*,'(''xrnse='',4f10.4)') 
ccc     +           xrnse+204.,atnos+204.,gnos+204.,xnois+204.
ccc      write(*,'(''QP?  ='',10x,3f10.4)') qpa,qpg,qpm
C
C     0.23026=1.0/4.34294
C
      PV=QPA*EXP((DUA-DU)*0.23026)
      SYGU=(PV*SUA)**2+((PV-QPA)*SMA)**2
      PV=QPG*EXP((DUG-DU)*0.23026)
      SYGU=SYGU+(PV*SUG)**2+((PV-QPG)*SMG)**2
      PV=QPM*EXP((DUM-DU)*0.23026)
      SYGU=SQRT(SYGU+(PV*SUM)**2+((PV-QPM)*SMM)**2)
      PV=QPA*EXP((DLA-DL)*0.23026)
      SYGL=(PV*SLA)**2+((PV-QPA)*SMA)**2
      PV=QPG*EXP((DLG-DL)*0.23026)
      SYGL=SYGL+(PV*SLG)**2+((PV-QPG)*SMG)**2    !  original code used SMA
CCCC  SYGL=SYGL+(PV*SLG)**2+((PV-QPG)*SMA)**2    !  as in this commented line
      PV=QPM*EXP((DLM-DL)*0.23026)
      SYGL=SQRT(SYGL+(PV*SLM)**2 +((PV-QPM)*SMM)**2)
C
C     RCVR SITE NOISE = TOTAL NOISE + ANTENNA EFFICENCY (ADDED TO
C                       SIGNAL WITH GAIN)
C
CQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
C------------    CHANGED 9/24/91  (LONG PATH RCVR EFF CORRECTION)  FJR
C------------          210 RCNSE = XRNSE + reff
  210 RCNSE = XRNSE
      XNOISE=XNOIS
      write(luo,'(''xnois='',2f10.4)') xnois,rcnse
CQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
      RETURN
      END
C--------------------------------
